# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='预定日期')),
                ('booking_time', models.IntegerField(choices=[(1, '8:00-9:00'), (2, '9:00-10:00'), (3, '10:00-11:00'), (4, '11:00-12:00)'), (5, '12:00-13:00'), (6, '13:00-14:00'), (7, '14:00-15:00'), (8, '15:00-16:00'), (9, '16:00-17:00'), (10, '17:00-18:00'), (11, '18:00-19:00'), (12, '19:00-20:00'), (13, '20:00-21:00')], verbose_name='预定时间段')),
            ],
            options={
                'verbose_name_plural': '预定关系表',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='会议室名称')),
                ('num', models.IntegerField(verbose_name='容纳人数')),
                ('addr', models.CharField(max_length=64, verbose_name='会议室地址')),
            ],
            options={
                'verbose_name_plural': '会议室表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.MeetingRoom', verbose_name='会议室'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('room_info', 'booking_date', 'booking_time')]),
        ),
    ]
